Log:
  Level: warning # Log level: none, error, warning, info, debug 
  AccessPath: # /etc/next-server/access.Log
  ErrorPath: # /etc/next-server/error.log
DnsConfigPath: # /etc/next-server/dns.json
RouteConfigPath: # /etc/next-server/route.json
InboundConfigPath: # /etc/next-server/custom_inbound.json
OutboundConfigPath: # /etc/next-server/custom_outbound.json
ConnectionConfig:
  Handshake: 4 # Handshake time limit, Second
  ConnIdle: 30 # Connection idle time limit, Second
  UplinkOnly: 2 # Time limit when the connection downstream is closed, Second
  DownlinkOnly: 4 # Time limit when the connection is closed after the uplink is closed, Second
  BufferSize: 64 # The internal cache size of each connection, kB
Nodes:
  - PanelType: "sspanel-old" # Panel type: sspanel-old, nextpanel-v1(wip)
    ApiConfig:
      ApiHost: "https://example.com"
      ApiKey: "xxx"
      NodeID: 1
      NodeType: vmess # Node type: vmess, trojan, shadowsocks, shadowsocks2022
      Timeout: 30 # Timeout for the api request
      SpeedLimit: 0 # Mbps, Local settings will replace remote settings, 0 means disable
      DeviceLimit: 0 # Local settings will replace remote settings, 0 means disable
      RuleListPath: # /etc/next-server/rulelist Path to local rulelist file
    ControllerConfig:
      ListenIP: 0.0.0.0 # IP address you want to listen
      SendIP: 0.0.0.0 # IP address you want to send pacakage
      UpdatePeriodic: 60 # Time to update the nodeinfo, how many sec.
      CertConfig:
        CertMode: dns # Option about how to get certificate: none, file, http, tls, dns. Choose "none" will forcedly disable the tls config.
        CertDomain: "node1.test.com" # Domain to cert
        CertFile: /etc/next-server/cert/node1.test.com.cert # Provided if the CertMode is file
        KeyFile: /etc/next-server/cert/node1.test.com.key
        Provider: # alidns # cloudflare # DNS cert provider, Get the full support list here: https://go-acme.github.io/lego/dns/
        Email: xxx@xxx.com
        DNSEnv: # DNS ENV option used by DNS provider
          # ALICLOUD_ACCESS_KEY: aaa
          # ALICLOUD_SECRET_KEY: bbb
          # CF_DNS_API_TOKEN: xxx
      EnableDNS: false # Use custom DNS config, Please ensure that you set the dns.json well
      DNSType: AsIs # AsIs, UseIP, UseIPv4, UseIPv6, DNS strategy
      DisableUploadTraffic: false # Disable upload traffic to API
      DisableGetRule: false # Disable get rule
      EnableProxyProtocol: false # Only works for WebSocket and TCP
      DisableIVCheck: false # Disable IV check
      DisableSniffing: false # Disable sniffing
      AutoSpeedLimitConfig:
        Limit: 0 # Warned speed. Set to 0 to disable AutoSpeedLimit (mbps)
        WarnTimes: 0 # After (WarnTimes) consecutive warnings, the user will be limited. Set to 0 to punish overspeed user immediately.
        LimitSpeed: 0 # The speedlimit of a limited user (unit: mbps)
        LimitDuration: 0 # How many minutes will the limiting last (unit: minute)
